/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedIndexRouteImport } from './routes/(unauthenticated)/index'
import { Route as unauthenticatedsignupCreateAccountRouteImport } from './routes/(unauthenticated)/(signup)/create-account'

const unauthenticatedIndexRoute = unauthenticatedIndexRouteImport.update({
  id: '/(unauthenticated)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthenticatedsignupCreateAccountRoute =
  unauthenticatedsignupCreateAccountRouteImport.update({
    id: '/(unauthenticated)/(signup)/create-account',
    path: '/create-account',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof unauthenticatedIndexRoute
  '/create-account': typeof unauthenticatedsignupCreateAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof unauthenticatedIndexRoute
  '/create-account': typeof unauthenticatedsignupCreateAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(unauthenticated)/': typeof unauthenticatedIndexRoute
  '/(unauthenticated)/(signup)/create-account': typeof unauthenticatedsignupCreateAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-account'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-account'
  id:
    | '__root__'
    | '/(unauthenticated)/'
    | '/(unauthenticated)/(signup)/create-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  unauthenticatedIndexRoute: typeof unauthenticatedIndexRoute
  unauthenticatedsignupCreateAccountRoute: typeof unauthenticatedsignupCreateAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)/': {
      id: '/(unauthenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof unauthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthenticated)/(signup)/create-account': {
      id: '/(unauthenticated)/(signup)/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof unauthenticatedsignupCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  unauthenticatedIndexRoute: unauthenticatedIndexRoute,
  unauthenticatedsignupCreateAccountRoute:
    unauthenticatedsignupCreateAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
