/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedIndexRouteImport } from './routes/(unauthenticated)/index'

const unauthenticatedIndexRoute = unauthenticatedIndexRouteImport.update({
  id: '/(unauthenticated)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof unauthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof unauthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(unauthenticated)/': typeof unauthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(unauthenticated)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  unauthenticatedIndexRoute: typeof unauthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)/': {
      id: '/(unauthenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof unauthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  unauthenticatedIndexRoute: unauthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
