name: Deploy Backend
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Add AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::481777894112:role/GitHubActionsRole
          aws-region: us-east-1
      - name: Test AWS credentials
        run: aws sts get-caller-identity
