name: Deploy Backend
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:
permissions:
  id-token: write # needed to request OIDC token
  contents: read
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Add AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: us-east-1
      - name: Test AWS credentials
        run: aws sts get-caller-identity
      - name: Install Node types
        run: npm install --workspace=backend --save-dev @types/node
      - name: Deploy backend to AWS
        run: |
          cd backend
          npx ampx pipeline-deploy --branch ${{github.ref_name}} --app-id didb9rcjmid9h
      - name: Upload amplify_outputs.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: amplify-outputs
          path: backend/amplify_outputs.json

  # build-frontend:
  #   runs-on: ubuntu-latest
  #   needs: deploy-backend
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: amplify-outputs
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Move amplify_outputs.json to frontend
  #       run: mv amplify_outputs.json frontend/amplify_outputs.json
  #     - name: Add AWS credentials
  #       uses: aws-actions/configure-aws-credentials@main
  #       with:
  #         audience: sts.amazonaws.com
  #         role-to-assume: ${{secrets.ROLE_ARN}}
  #         aws-region: us-east-1
  #     - name: Upload build artifacts to S3
  #       run: |
  #         cd frontend
  #         npm run build
  #         aws s3 sync ./dist s3://chat-app-frontend-hostingbucket-1h6gk4x1f2s9w
